config/routes.rb
Rails.application.routes.draw do
  resources :documents do 
    member do
      get :doc_preview
    end
  end
  root to: 'documents#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/document.rb
class Document < ApplicationRecord
  has_one_attached :doc
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController

  before_action :set_document, only: %i[ show edit update destroy doc_preview]

  # GET /documents or /documents.json
  def index
    @documents = Document.all
  end

  # GET /documents/1 or /documents/1.json
  def show
    respond_to do |format|
      format.html
      format.docx do

        @file_temp = Tempfile.new("document_tmp_#{@document.id}", "#{Rails.root}/tmp")
        @file_temp.binmode
        
        @document.doc.download {|chunk| @file_temp.write(chunk) }

        # Initialize DocxReplace with your template
        doc = DocxReplace::Doc.new(@file_temp.path, "#{Rails.root}/tmp")

        # Replace some variables. $var$ convention is used here, but not required.
        doc.replace("%{company_cin_no}", "This is cin number")
        doc.replace("%{company_address}", "This is the company address")
        doc.replace("%{company_contact_email}", "This is company email")

        # Replace multiple occurrences
        doc.replace("%{branch_name}", "This is branch name", true)

        # Write the document back to a temporary file
        # tmp_file = Tempfile.new("document_#{@document.id}", "#{Rails.root}/tmp")
        doc.commit#(tmp_file.path)
        # doc_pdf_dir = "#{Rails.root}/tmp/pdf_temp_#{@document.id}.pdf"
        # Libreconv.convert(@file_temp.path, doc_pdf_dir)

        # Respond to the request by sending the temp file
        send_file @file_temp.path, filename: "doc_#{@document.id}_report.docx", disposition: 'preview'
      end
    end
  end

  def doc_preview
    @file_temp = Tempfile.new("document_tmp_#{@document.id}", "#{Rails.root}/tmp")
    @file_temp.binmode    
    @document.doc.download {|chunk| @file_temp.write(chunk) }

    # Initialize DocxReplace with your template
    temp_doc = DocxReplace::Doc.new(@file_temp.path, "#{Rails.root}/tmp")

    # Replace some variables. $var$ convention is used here, but not required.
    temp_doc.replace("%{company_cin_no}", "This is cin number")
    temp_doc.replace("%{company_address}", "This is the company address")
    temp_doc.replace("%{company_contact_email}", "This is company email")

    # Replace multiple occurźences
    temp_doc.replace("%{branch_name}", "This is branch name", true)

    temp_doc.commit(@file_temp.path)

    # d = Docx::Document.open(@file_temp.path)


    # @data = d.to_html.html_safe
    @data = temp_doc.to_html

    File.delete(@file_temp.path) if File.exist?(@file_temp.path)

  end

  # GET /documents/new
  def new
    @document = Document.new
  end

  # GET /documents/1/edit
  def edit
  end

  # POST /documents or /documents.json
  def create
    @document = Document.new(document_params)

    respond_to do |format|
      if @document.save
        format.html { redirect_to document_url(@document), notice: "Document was successfully created." }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1 or /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to document_url(@document), notice: "Document was successfully updated." }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1 or /documents/1.json
  def destroy
    @document.destroy

    respond_to do |format|
      format.html { redirect_to documents_url, notice: "Document was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def document_params
      params.require(:document).permit(:doc)
      # params.fetch(:document, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_document.html.erb
<div id="<%= dom_id document %>">
  <% if document.doc.attached? %>
    <%= document.id %> <%= link_to 'File', url_for(document.doc) %>
    <%= link_to "Preview", doc_preview_document_path(document.id) %>
    
  <% else %>
    No File attached
  <% end %>
</div>

app/views/documents/_form.html.erb
<%= form_with(model: document) do |form| %>
  <% if document.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
        <% document.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.file_field :doc %>
  </div>
  <br>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/documents/doc_preview.html.erb
<%=@data%>

app/views/documents/edit.html.erb
<h1>Editing document</h1>

<%= render "form", document: @document %>

<br>

<div>
  <%= link_to "Show this document", @document %> |
  <%= link_to "Back to documents", documents_path %>
</div>

app/views/documents/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Documents</h1>

<div id="documents">
  <% @documents.each do |document| %>
    <%= render document %>
    <p>
      <%= link_to "Show this document", document %>
    </p>
    <hr>
  <% end %>
</div>

<%= link_to "New document", new_document_path %>

app/views/documents/new.html.erb
<h1>New document</h1>

<%= render "form", document: @document %>

<br>

<div>
  <%= link_to "Back to documents", documents_path %>
</div>

app/views/documents/show.html.erb
<p style="color: green"><%= notice %></p>
https://view.officeapps.live.com/op/embed.aspx?src=<%=document_url(@document, format: "docx", embedded: true)%>
<%= render @document %>
<iframe src="https://view.officeapps.live.com/op/embed.aspx?src=<%=document_url(@document, format: "docx", embedded: true)%>"></iframe>


<div>
  <%= link_to "Edit this document", edit_document_path(@document) %> |
  <%= link_to "Back to documents", documents_path %>

  <%= button_to "Destroy this document", @document, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DocxTemplates</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>